# Generated by Django 4.2.5 on 2023-10-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_productingredient_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=250, verbose_name='User session ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], max_length=100, verbose_name='Status of order')),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], max_length=100, verbose_name='Delivery method')),
                ('total_amount', models.IntegerField(verbose_name='Order total amount')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('total_price', models.IntegerField(verbose_name='Total price of product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'Orders Products',
                'db_table': 'order_products',
            },
        ),
    ]
