# Generated by Django 4.2.5 on 2023-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product name')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='Image')),
                ('price_decimal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Product price (Decimal)')),
                ('weight_grams', models.IntegerField(default=0, verbose_name='Weight in grams')),
                ('weight_kilocalories', models.IntegerField(default=0, verbose_name='Weight in kilocalories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
